# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9cdf38509ec423d6b5f2b56211a1a1f21375d2e2b09e335161dd4d7121278c27bae8d823e0239f96498c5dfc8e8b0b07484fc9e619609af23d3c4877b06c5544

test:
  secret_key_base: 3bbd7bcb48146fe0ac4d2a687942e6f682a9e18a8e0cb5a25d9f471fb4fe14c7ef3bb307494389db44db5edaedcb6238a2d4539b058d29ddafc19e71b8051d3c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
